version: '3'
services:
  app:
    build: .
    volumes:
     - ../app:/app
     - ../api:/api
  admin:
    build: .
    volumes:
     - ../admin:/app
     - ../api:/api
  maintenance:
    build: .
    volumes:
     - ../maintenance:/app